### ISSUE TITLE
extra_attributes does not work

### ISSUE THREAD

**Issue by YiniXu9506** [algolia/docsearch-configs#1036]
# Do you want to request a **feature** or report a **bug**?
**bug**

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= pingcap

## What is the **current** behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*
I made a pull request #1034, which is adding an extra_attributes for facetFilters. The API does not work.

```
index.search(
      {
        query: urlParams.get('q'),
        hitsPerPage: 10,
        facetFilters: ['version:dev'],
      },

      (err, {hits} = {}) => {
        if(err) throw err;

        console.log('hits are:', hits)
      })
)
```
Then I get nothing:
![image](https://user-images.githubusercontent.com/34967660/65497208-6a628380-deec-11e9-8f32-fb70be0dd520.png)

## What is the **expected** behaviour?
I expect the results are docs in version 3.0

#### What have you tried to solve it?
I tried to filter results tags with `en`, 
```
index.search(
      {
        query: urlParams.get('q'),
        hitsPerPage: 10,
        facetFilters: ['tags:en'],
      },

      (err, {hits} = {}) => {
        if(err) throw err;

        console.log('hits are:', hits)
      })
)
```
and get the hits:
![image](https://user-images.githubusercontent.com/34967660/65497503-f07eca00-deec-11e9-82df-661a58a9887b.png)

### Any other feedback / questions ?

@s-pace PTAL, thanks!

**Comment by s-pace** [comment]
Please give it a new try. I am pretty sure the update of your configuration solved this issue since `version` attribute was not a `facetFilters`.

DISCLAIMER: The time required to crawl you whole website is high. We might ask you to either reduce the scope of crawl (e.g. limit to the latest versions) or [run the crawler on your own infrastructure with your own Algolia account](https://community.algolia.com/docsearch/run-your-own.html#running-the-crawler).
