### ISSUE TITLE
How to set page_rank

### ISSUE THREAD

**Issue by YiniXu9506** [algolia/docsearch-configs#1085]
# Do you want to request a **feature** or report a **bug**?
**feature**

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= pingcap

## What is the **current** behaviour?
I run the  crawler by myself. The configuration I set for `start_urls` as the one in the sreenshot. Set `page_rank = 5` to `https://pingcap.com/docs-cn/v3.0/releases/` and nothing to `https://pingcap.com/docs-cn/v3.0/`. But hits of `https://pingcap.com/docs-cn/v3.0/releases/ ` still come first than some hits of `https://pingcap.com/docs-cn/v3.0/`

![image](https://user-images.githubusercontent.com/34967660/67731875-92398f80-fa34-11e9-90f0-7973138f4c4d.png)

![image](https://user-images.githubusercontent.com/34967660/67732518-9797d980-fa36-11e9-9f66-be7ea4fa492c.png)

## What is the **expected** behaviour?
I expect all hits of `https://pingcap.com/docs-cn/v3.0/ ` except `https://pingcap.com/docs-cn/v3.0/releases/` come first. Then show the hits of `https://pingcap.com/docs-cn/v3.0/releases/`. 

I am wondering is the configurations I set is incorrect. @s-pace  PTAL, thanks!

**Comment by s-pace** [comment]
👋 @YiniXu9506 

`page_rank` is integrated as part of the custom ranking criteria. This is the last criterion used int the Algolia __tie-breaking algorithm__ approach. `page_rank` is here to decide between hits in case of a tie. You will need to dig into [the Algolia documentation to better understand the whole reasoning behing](https://www.algolia.com/doc/guides/managing-results/must-do/custom-ranking/).

The hits you want to be sorted out differently are not in this tie situation from a relevancy POV. This the reason why custom_ranking is ineffective in this situation.

_Pro tip:_ Since you are running the crawler on you own with your own Algolia plan, you can access the  browse tab from the dashboard. You should use the trophy tooltip available from the bottom right-hand side corner. It will help you to tweak the Algolia strategy and understand how DocSearch is set up by default:

![image](https://user-images.githubusercontent.com/32097720/67761778-455db500-fa44-11e9-91b3-2e6eca99bdaf.png)


Closing this issue as it is related to a broader use of Algolia. Feel free to reach out support@algolia.com if you need further guidance.

Thanks
