### ISSUE TITLE
Catch malicious config PRs

### ISSUE THREAD

**Issue by michaelyfan** [algolia/docsearch-configs#1176]
# Do you want to request a **feature** or report a **bug**?

N/A

### If it is a DocSearch index issue, what is the related `index_name` ?

N/A

## What is the **current** behaviour?

There doesn't seem to be a way to verify that a Github user making an PR to a company's configuration is actually from that company. A malicious user impersonating someone from my company could make a PR with reasonable-looking but totally nonsensical changes (ex. random CSS selectors) that would affect our search, and get it merged in after some minor technical discussion. 

## What is the **expected** behaviour?

There is some sort of verification for users who make PRs to make sure they actually come from the company. 

#### What have you tried to solve it?

N/A

#### Any quick clues?

N/A

### Any other feedback / questions ?

Are there measures currently in place to prevent malicious impersonation?

**Comment by s-pace** [comment]
Thanks for sharing @michaelyfan 

Feel free to send us the GitHub handles of the only authorised people from your team. We will only allow these folks to edit your configuration.

We always check that the PR makes sense and that it is not completely changing the configuration. Furthermore once the crawl is done we always make sure that the search experience is better than the previous one. We will revert a PR that doesn't bring any value and/or break the search experience e.g. https://github.com/algolia/docsearch-configs/commit/f740a6354c27bcbb34fe15ceb819e8bee9c892a4

We will keep this feature request in our backlog. Closing it in the meantime since this repo is only dedicated to configuration issues.
