### ISSUE TITLE
Content tagged in the new class not searchable

### ISSUE THREAD

**Issue by ArshRai17** [algolia/docsearch-configs#2033]
# Do you want to request a **feature** or report a **bug**?

### If it is a DocSearch index issue, what is the related `index_name` ?

@s-pace , My recent PR (#2016) was to make certain code samples searchable. It has been over 6 days, but the code snippets are still not searchable.

`index_name`=solace

## What is the **current** behaviour?

Cannot search code samples that are inside the `<span class="sample_snippet"></span>
`
*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

## What is the **expected** behaviour?

Code samples inside `<span class="sample_snippet"></span>` should be indexed and searchable.

**Comment by s-pace** [comment]
👋 @ArshRai17 

I have deep dived into your issue and it seems that #2016 doesn't' help because you added the selector `.sample_snippet` to the wrong set of selectors. You added this selector to the set `learning_center` while this set of selectors is only applied to pages with an URL matching the following `start_url`:

```json
{
      "url": "https://cloud.solace.com/learn/",
      "selectors_key": "learning_center",
      "tags": [
        "learning_center"
      ]
}
```

`https://docs.solace.com/Solace-PubSub-Messaging-APIs/API-Developer-Guide/Java-API-Best-Practices.htm` is not on the same subdomain as `https://cloud.solace.com/learn/`. This page is parsed thanks to the `default` set of selectors instead. 

I would recommend to move the selector `.sample_snippet` to the `default` one. It will solve this issue.

**Comment by s-pace** [comment]
It seems that  #2076 solved this issue. Feel free to reopen it if needed.

**Comment by ArshRai17** [comment]
Thanks, for your help @s-pace
