### ISSUE TITLE
Update modelica.json search index

### ISSUE THREAD

**Issue by beutlich** [algolia/docsearch-configs#2068]
modelica.json should yield more search hits. Can you please update. Thanks.

**Comment by beutlich** [comment]
When searching for example for "squashed", do you have an idea why there is no search hit? I'd expected to get a search hit https://doc.modelica.org/Modelica%204.0.0/Resources/helpOM/Modelica.UsersGuide.ReleaseNotes.VersionManagement.html

**Comment by s-pace** [comment]
The search does work for the query `squashed`:

![image](https://user-images.githubusercontent.com/32097720/87148359-8d5cf900-c2ae-11ea-8487-532f65b3aff6.png)

It does redirect to the exact page you are referring too. Can you double check please? It might be due to a wrong usage of facetFilters or the crawl not being fresh enough.
