### ISSUE TITLE
Application: ava.antv.vision

### ISSUE THREAD

**Issue by jiazhewang** [algolia/docsearch-configs#2740]
Hi, I am adding algolia search to our opensource project: https://ava.antv.vision/

I have submitted the application form: https://docsearch.algolia.com/apply/

Should I sumbit a PR for it?

Look forward to your reply. thx!

**Comment by shortcuts** [comment]
Hi,

It seems like the URL is not available anymore, could you let me know when it will be?

You can submit a PR with your config file and I'll accept it once every step of the [apply](https://docsearch.algolia.com/apply/) section has been completed.

Thanks for your interest, have a nice day.

**Comment by jiazhewang** [comment]
> Hi,
> 
> It seems like the URL is not available anymore, could you let me know when it will be?
> 
> You can submit a PR with your config file and I'll accept it once every step of the [apply](https://docsearch.algolia.com/apply/) section has been completed.
> 
> Thanks for your interest, have a nice day.

Hi, @shortcuts 

I have fixed the URL and submitted the PR https://github.com/algolia/docsearch-configs/pull/2764

thx!

**Comment by shortcuts** [comment]
Hi @jiazhewang,

Thanks for the PR!
As of now, your application got rejected because of the following reasons:
- Your website looks to be in a building stage.
- We spotted some “lorem ipsum” content OR blank page OR WIP markup.

Once your documentation as been filled, feel free to [apply](https://docsearch.algolia.com/apply/) again and I'll merge the PR!

Have a nice day

**Comment by jiazhewang** [comment]
Hi @shortcuts ,

My website has been filled and I've applied again. Could u merge the PR, plz.

Thank you!
