### ISSUE TITLE
Page ranking not working as expected

### ISSUE THREAD

**Issue by ArshRai17** [algolia/docsearch-configs#3028]
# Do you want to request a **feature** or report a **bug**?

Page ranking is not working as expected.

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=solace.json

## What is the **current** behaviour?

This page is ranked highest when someone searches for "Security"  https://docs.solace.com/MQTT-311-Prtl-Conformance-Spec/Security.htm#_Toc43086497. We don't want that. Instead, we want this https://docs.solace.com/Security/Security-Solace.htm to be ranked higher when someone searches for "Security".

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

Search for "Security" in docs.solace.com

## What is the **expected** behaviour?
Based on this [pull request](https://github.com/algolia/docsearch-configs/commit/fa331cd1d5d6c161cef1d1a7570fe60e198838da#diff-e2c05f42f37a01b97c416e6b56c712664e10a25e1747c5ad8d13f954468bd7f2) I was hoping for the following behaviour when someone searches for "Security":
1. This page to be ranked highest https://docs.solace.com/Security/Security-Solace.htm. Top appear first on the search
2. This page to be ranked lower than the above, so appears at the bottom of the search https://docs.solace.com/MQTT-311-Prtl-Conformance-Spec/Security.htm#_Toc430864975 

#### What have you tried to solve it?
Created the following [pull request](https://github.com/algolia/docsearch-configs/commit/fa331cd1d5d6c161cef1d1a7570fe60e198838da#diff-e2c05f42f37a01b97c416e6b56c712664e10a25e1747c5ad8d13f954468bd7f2)

**Comment by shortcuts** [comment]
Hi @ArshRai17,

It looks like the results from `https://docs.solace.com/MQTT-311...` have a weight of 90 compared to the one from `https://docs.solace.com/Security/...` that have a weight of 80.

This is not only due to the `page_rank` but also the position of the records, the number of matches etc.

I think the solution is just to add more weight to these results, that's what I've done here: https://github.com/algolia/docsearch-configs/pull/3034

You should be able to see the results in the next 24 hours,
Feel free to let me know,
Have a nice day
