### ISSUE TITLE
[openhab] Obsolete index

### ISSUE THREAD

**Issue by ghys** [algolia/docsearch-configs#3137]
# Do you want to request a **feature** or report a **bug**?

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=openhab

## What is the **current** behaviour?

On openhab.org, when searching with the search box in the navigation bar, the search results contain pages that don't exist anymore.
For example, trying "http" yields "HTTP binding v1" as first results, which leads to a 404 (the page was indeed removed).
This was first reported on December 23rd so any indexing delay should have elapsed by now.

## What is the **expected** behaviour?

The search should give current results.

#### What have you tried to solve it?

https://www.algolia.com/apps/.../explorer/browse/openhab?query=http
Tried this button but I'm not sure it does what I think:
![image](https://user-images.githubusercontent.com/2004147/103484861-3e71c580-4df2-11eb-8635-6d61ab057021.png)

#### Any quick clues?

We migrated the site from VuePress v0 to VuePress v1 when we released our latest major version 2 weeks ago, so it could be related.

### Any other feedback / questions ?

We were in contact with @Shipow and @s-pace to add the site to DocSearch at the time: https://github.com/openhab/website/issues/73

**Comment by shortcuts** [comment]
Hi,

The `refresh index` is only refreshing the frontend (re-fetching records) but not triggering a crawl. 

The issue was indeed the migration part, the selectors changed from `.content` to `.content__default`.

I've fixed it here: https://github.com/algolia/docsearch-configs/pull/3138

Feel free to open a PR if there's any issues,
Have a nice day.
