### ISSUE TITLE
[cloudflare-workers-v2] Only root page is being indexed

### ISSUE THREAD

**Issue by signalnerve** [algolia/docsearch-configs#3208]
# Do you want to request a **feature** or report a **bug**?

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=cloudflare-workers-v2

## What is the **current** behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

Searching in our Cloudflare Workers documentation only shows results from the index page:

1. Go to https://developers.cloudflare.com/workers/
2. Search any query, such as "workers"
3. The results are only based on content from the index page (https://developers.cloudflare.com/workers/)

## What is the **expected** behaviour?

As specified in our docsearch config, we have a sitemap for the docs that specify many other URLs: https://developers.cloudflare.com/workers/sitemap.xml

#### What have you tried to solve it?

n/a not sure what we can do on our end to fix

#### Any quick clues?

n/a

### Any other feedback / questions ?

n/a

**Comment by shortcuts** [comment]
Hi,

I've pushed an update that take count of the client side rendering in case it could fix your issue. See https://github.com/algolia/docsearch-configs/pull/3213

You should be able to see the changes in the next 24 hours.

As everything is looking good on our side, could you please send me the expected endpoints for the query `workers`  if the issue is still there?

Have a nice day.
