### ISSUE TITLE
URLs not on sitemap are indexed

### ISSUE THREAD

**Issue by jayhesselberth** [algolia/docsearch-configs#371]
# Do you want to request a **feature** or report a **bug**?

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= pkgdown

## What is the **current** behaviour?

Files that are not in the sitemap.xml are included in the index.

## What is the **expected** behaviour?

Files that are not in the sitemap.xml *should not* be included in the index.

## Summary

The pkgdown index includes the "Contributor Code of Conduct" page, which is not in the [sitemap.xml](http://pkgdown.r-lib.org/sitemap.xml).

To reproduce, go to the [pkgdown website](http://pkgdown.r-lib.org/) and search for "Contributor"; it's the first result.

The [pkgdown config](https://github.com/algolia/docsearch-configs/blob/master/configs/pkgdown.json) lists the sitemap.xml. Why is this page (and presumably other unwanted pages) included in the index?

From https://github.com/r-lib/pkgdown/issues/626#issuecomment-379373606

**Comment by s-pace** [comment]
👋 @jayhesselberth Thank you for this complete issue.

The issue existed because you didn't [update the config](https://github.com/r-lib/pkgdown/issues/608). I have updated and deployed. Let me know if it helps.

We will use the [pkgdown config](https://github.com/algolia/docsearch-configs/blob/master/configs/pkgdown.json) as pattern for other pkgdown user. Please don't forget to edit it. It will be our main example CC @hadley
