### ISSUE TITLE
All results page empty (config update needed?)

### ISSUE THREAD

**Issue by TomBrien** [algolia/docsearch-configs#3717]
# Do you want to request a **feature** or report a **bug**?

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= `companion-home-assistant`

## What is the **current** behaviour?
 
Searching a term and using a "See all _n_ results" link to go to <https://companion.home-assistant.io/search?q=app> produces a page with no results.

## What is the **expected** behaviour?

Page showing all results

#### Any quick clues?

Searching old issues here and on Docusaurus GitHub suggests the config requires migrating to a newer version. Site(s) are running Docusaurus V2

Also applies to:
- `home-assistant-dev`
- `data-home-assistant`

**Comment by shortcuts** [comment]
Hi @TomBrien,

All fixed in https://github.com/algolia/docsearch-configs/pull/3718, https://github.com/algolia/docsearch-configs/pull/3719 and https://github.com/algolia/docsearch-configs/pull/3720

Indeed, with the migration of Docusaurus v2, meta tags are added to the website and used as facetFilters.

If you have any other configuration that have the same issue, you can also apply these changes and open a pull request!

You should see the changes in the next 24 hours,
Have a nice day!

**Comment by TomBrien** [comment]
Thanks
