### ISSUE TITLE
Algolia does not search for what I typed, and instead tries to guess what I wanted. It gets it wrong.

### ISSUE THREAD

**Issue by unikitty37** [algolia/docsearch-configs#4081]
At https://www.tiptap.dev/examples/default, searching for `editor-content` does not find matches for the term `editor-content`, instead finding matches for the term `editor content`. Wrapping the term in quotes does not fix this

I was specifically looking for documentation of the `<editor-content>` tag, as mentioned in the code example at https://www.tiptap.dev/installation/vue2/#3-create-a-new-component, but Algolia keeps deciding it knows better than me what I want to search for.

At the very least, exact matches should appear above inexact ones — so any pages containing `editor-content` should appear above pages only containing `editor content`.

Is there a way of forcing Algolia to search for the *exact* string that I've entered? If so, could it be indicated clearly in the search box? (It would be more useful than the line telling me to use cursor keys, Enter, and Esc, as this is expected behaviour that shouldn't need documenting :)

**Comment by shortcuts** [comment]
Hi,

This issue is not related to our engine, but the fact that this content isn't indexed. As you can see in [the concerned config](https://github.com/algolia/docsearch-configs/blob/master/configs/ueberdosis_tiptap.json), we don't index `code` or `span` tags.

If you are a maintainer of this project, please feel free to update your config by opening a pull request!

> Is there a way of forcing Algolia to search for the exact string that I've entered? If so, could it be indicated clearly in the search box?

It is not possible, since this is the default behavior. Searched text will **always** have a better match than a query suggestion based on a typo.

Hope this answers your question!
