### ISSUE TITLE
[ditsmod] Missing results for language-specific queries

### ISSUE THREAD

**Issue by KostyaTretyak** [algolia/docsearch-configs#4137]
I use docusaurus for my documentation. In the configuration file, I specify that I want to use contextual search:

```text
module.exports = {
  // ...
  themeConfig: {
    // ...
    algolia: {
      apiKey: '86bdb4ef75a986e9aa998503dfc64d23',
      indexName: 'ditsmod',
      contextualSearch: true,
      searchParameters: { facetFilters: ["type:content", "language:LANGUAGE"] },
    },
  },
};
```

That is for algolia I pass `facetFilters: ["type:content", "language:LANGUAGE"] `, but in this case, algolia does not return any results (see http://ditsmod.github.io/).

I tried to read the documentation at https://www.algolia.com/doc/api-reference/api-parameters/#overview, but didn't understand what to do to make the search work. Please tell me what I'm doing wrong, or point to the documentation where I can read the language-specific parameters.

**Comment by shortcuts** [comment]
Hi,

This issue is related to Docusaurus and not DocSearch, but here's an explanation:

Using the Docusaurus option [contextual search](https://docusaurus.io/docs/search#contextual-search) will directly send the `facetFilters` such as `version`, `language`, etc. so you don't have to pass any `searchParameters`. See the response from the network tab when searching on your site: 
```json
facetFilters: ["language:uk",["docusaurus_tag:default","docusaurus_tag:docs-default-current"],"type:content","language:LANGUAGE"]"}]}
```

(Also, you might not have results returned with the `contextualSearch` option, see this issue: https://github.com/facebook/docusaurus/issues/4555#issuecomment-812569108, I'd suggest you to disable it for the next 24 hours until a new crawl has been completed!)
