### ISSUE TITLE
[activeui] "Index does not exist" 404 when searching in the docs

### ISSUE THREAD

**Issue by antoinetissier** [algolia/docsearch-configs#4277]
Hi, our docsearch has stopped working, yielding 404s when querying the index.

### `index_name`

`index_name`= activeui

## What is the **current** behaviour?

Connect https://activeviam.com/activeui/documentation/4.3.17/index.html, open the dev tools, and type something in the searchbar.
It will yield a 404, saying that the index does not exist:
![image](https://user-images.githubusercontent.com/29061952/123638358-60875600-d81f-11eb-97f1-3e651889d3b8.png)

## What is the **expected** behaviour?

There should be an index, and the search should yield results.

Any help would be appreciated.

**Comment by slumbering** [comment]
Hi, same here ! Thanks for your help

**Comment by shortcuts** [comment]
Hi,

We had an internal issue for the indices with outdated configs

**Comment by shortcuts** [comment]
Hi, thanks for reporting this.

@antoinetissier, could you please let me know for how long your index has been missing?

We had an issue on our DocSearch crawler around two weeks ago but we re-ran an indexing on [all of the active configs](https://github.com/algolia/docsearch-configs/tree/master/configs) right after we fixed it. 
For `activeui`, it looks like the crawl has just finished, a new one will be started in the next 24 hours.

**If your index doesn't work yet**:
- It requires client-side rendering and it's a pretty big website: it's being crawled, feel free to mention me so I can track the progress.
- Your config file is outdated, please update it and submit a PR on this repository, otherwise the crawl won't work.

@slumbering could you please let me know which website is concerned?

**Comment by slumbering** [comment]
Hi @shortcuts , thanks for your message.

My index name is : daggosaurus

The website is docs.dagger.io

Thanks again for your help

**Comment by shortcuts** [comment]
> The website is docs.dagger.io

It seems that it is private and therefore not supported by our [DocSearch policy](https://docsearch.algolia.com/docs/who-can-apply), sorry.

**Comment by slumbering** [comment]
@shortcuts. You're right. We've implemented the auth recently but it's temporary. When this auth will be removed, does my index will still exist and then works again ? Thanks

**Comment by shortcuts** [comment]
Yep!

**Comment by slumbering** [comment]
Fantastic :). Thanks @shortcuts for your help.
Have a great day

**Comment by antoinetissier** [comment]
Hi @shortcuts,

Thanks a lot for the feedback, we don't have the 404 anymore !

However, while the docsearch is working well for the most recent version of the doc now, it yields no results for previous versions, even though there is a single index with facet filters, as shown in the following gif:
![previousVersionsNotWorking](https://user-images.githubusercontent.com/29061952/123771963-c7624900-d8cb-11eb-995a-7cfa357bc28c.gif)

We have already had an issue in the past where the docsearch was working for some versions and not others: https://github.com/algolia/docsearch-configs/issues/3449

Is there any way that we can make it more robust so that we don't have this issue in the future ?

**Comment by antoinetissier** [comment]
Following up on this: I was wondering if the problem seen here and in https://github.com/algolia/docsearch-configs/issues/3449 of `docsearch` working only for some versions and not others (seeminly in a flaky way) could be a size issue ?

You were mentioning in https://github.com/algolia/docsearch-configs/issues/3449#issuecomment-775305233 that we could not run the crawler ourselves without a paid plan for example because the index was too big.

Out of curiosity, could you share the size of our index and the one of [activepivot](https://github.com/algolia/docsearch-configs/blob/master/configs/activepivot.json) ? It's another team in our company and they have never had any problems.

**Comment by shortcuts** [comment]
Hey @antoinetissier,

There might be some inconsistencies due to client-side rendering on huge indices like the `activeui` one, and I think in that case, the re-index timed out. It seems that some of the pages have been ignored for no reason, while running it locally picks up those URLs.

I'm actually testing with and without client-side rendering to see if there's differences, I'll push the config once those have been finished.

`activeui`: ~200k records
`activepivot`: ~100k records

**Comment by antoinetissier** [comment]
Thanks a lot @shortcuts. In fact I removed a lot of our old doc to see if it helps with the issue. We were at 500k records before it seems (according to #3449 (comment)). So hopefully it's better now !

**Comment by shortcuts** [comment]
After doing some tests, it looks like there's no differences with the client-side rendering, is it still used on your website? 

Hopefully, https://github.com/algolia/docsearch-configs/pull/4300 will fix everything!

**Comment by shortcuts** [comment]
@antoinetissier A new crawl has been queued, feel free to re-open if you see some other inconsistencies!
