### ISSUE TITLE
[functionmesh] Can't search for anything

### ISSUE THREAD

**Issue by tuteng** [algolia/docsearch-configs#4303]
Test: https://deploy-preview-81--function-mesh.netlify.app/docs/next/

Site: functionmesh.io 

Can't search for anything

**Comment by MateuszDabrowski** [comment]
Check in the Algolia Dashboard whether you can see your index and any result.
I just found out it was deleted (along with the whole history and search results).

**Comment by shortcuts** [comment]
Hi @tuteng,

You need to have the DocSearch plugin enabled during a crawl (every 24 hours), in order to make the search work in Docusaurus v2 with the `contextualSearch` option.

Disabling the option will return the right results.

@MateuszDabrowski it seems that your website returns 503 errors in our crawler, is there any restrictions on your side?

**Comment by shortcuts** [comment]
Closing this issue since the second question isn't related.
