### ISSUE TITLE
[activeui] searching in the docs yields no results.

### ISSUE THREAD

**Issue by messaooudi** [algolia/docsearch-configs#4364]
Following up on this [issue](https://github.com/algolia/docsearch-configs/issues/4277).

### Current behaviour :
Connect https://activeviam.com/activeui/documentation/5.0.0/, type something in the searchbar.
It will yield empty results.

### Expected behaviour:
The search should yield results.

I am wondering what's the crawl status on 5.0.0 version ?
Any help would be appreciated.

**Comment by messaooudi** [comment]
@shortcuts could you please check if the `5.0.0 version` was crawled ?

**Comment by shortcuts** [comment]
Hey @messaooudi,

The last crawl ended around ~21hours ago but no `5.0.0` version were crawled, only `4.x.x` versions.

I'll try to run the crawl locally to see if it's picked up by the sitemap, worst case would be to add the `5.0.0` sitemap to the `sitemap_urls` in your config.

**Comment by messaooudi** [comment]
Hey @shortcuts, thanks for your reply, 

Our [sitemap_urls](https://github.com/algolia/docsearch-configs/blob/9454e2adbc8acfddae32a8e0bf7e1682254c0a46/configs/activeui.json#L4) contains one sitemap URL, in which we specify a sitemap URL for each version (4.x.x and 5.x.x).

FYI : in the `4.x.x` versions we were using `docusaurus 1` , and in the `5.0.0` version we upgraded to `docusaurus 2`

**Comment by shortcuts** [comment]
> FYI : in the 4.x.x versions we were using docusaurus 1 , and in the 5.0.0 version we upgraded to docusaurus 2

You should update your config to use the [selectors_key](https://docsearch.algolia.com/docs/config-file/#selectors_key-tailor-your-selectors) option then, in order to make the URLs matching the `5.x.x` pattern target the [docusaurus v2 selectors](https://github.com/algolia/docsearch-configs/blob/master/configs/docusaurus-2.json#L11-L25). You can also add all of the [docusaurus v2 settings](https://github.com/algolia/docsearch-configs/blob/master/configs/docusaurus-2.json#L26-L43) to the config (no need to keep the ones from the V1) so that you can take advantage of the [contextualSearch option](https://docusaurus.io/docs/search#contextual-search) on your v5 doc :D

**Comment by messaooudi** [comment]
Indeed , our HTML doc structure does not match the selectors in our config, it does match the  docusaurus-2 [selectors](https://github.com/algolia/docsearch-configs/blob/master/configs/docusaurus-2.json#L11-L25) config .
Can you please update our [selectors](https://github.com/algolia/docsearch-configs/blob/9454e2adbc8acfddae32a8e0bf7e1682254c0a46/configs/activeui.json#L12-L25) config to match the one from [docusaurus-2](https://github.com/algolia/docsearch-configs/blob/master/configs/docusaurus-2.json#L11-L25) and trigger a crawel ?

**Comment by messaooudi** [comment]
@shortcuts any chance you can update our config , I wasn't able to open a PR in that regard.

**Comment by messaooudi** [comment]
@shortcuts here is the [PR](https://github.com/algolia/docsearch-configs/pull/4426).
