### ISSUE TITLE
Integrating a subdomain in docsearch

### ISSUE THREAD

**Issue by iamsameeraliyanage** [algolia/docsearch-configs#4525]
We are already using the docsearch open source plan for the search functionality in [https://ballerina.io/](url).
Also, in addition to this, we need another separate docsearch functionality to search content in the subdomain [https://blog.ballerina.io/](url).

How to configure this?

@nex3 
@dennisreimann 
@sqs 
@jwoertink 
@hadley 

# Do you want to request a **feature** or report a **bug**?

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=

## What is the **current** behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

**Comment by shortcuts** [comment]
Hey @iamsameeraliyanage,

Since the blog is already indexed in your current index: https://github.com/algolia/docsearch-configs/blob/master/configs/ballerina.json#L29-L41

You can update the DocSearch instance on this page: https://blog.ballerina.io/ to match [this implementation](https://codesandbox.io/s/jolly-sun-rrt7q?file=/src/index.js), which will only search for results in the `ballerina_blog` tags

**Comment by iamsameeraliyanage** [comment]
**This worked for us. Thank you so much for the prompt response. Highly appreciate it.**
