### ISSUE TITLE
near-sdk.io index

### ISSUE THREAD

**Issue by volovyk-s** [algolia/docsearch-configs#4646]
Hey @shortcuts !  We want to have a separate index for https://www.near-sdk.io. I have applied for it here: https://docsearch.algolia.com/apply/
But I never got any response.
We need to release this website shortly, can you please help me with this?
I have applied with this email: serhii@near.org

**Comment by shortcuts** [comment]
Hey @volovyk-s,

As I thought it was solved after https://github.com/algolia/docsearch-configs/pull/4634 which handles both website, I closed your ticket, sorry!

Since it concern the same project as `near`, you can handle it in the same config so that you don't need to wait for our approval, different credentials, etc.

With the following config: https://gist.github.com/shortcuts/2ba87b09cb6fae3ecf279b32856fdf25
You can use the same credentials but filtering the search on the website: https://codesandbox.io/s/awesome-nash-mxhhr?file=/src/index.js

**Comment by shortcuts** [comment]
Hey @volovyk-s,

Any help needed on that side?

**Comment by volovyk-s** [comment]
Thank you @shortcuts ! It worked. I was sure that we need to create a new index for it.
