### ISSUE TITLE
`#main-content` getting appended to hit URLs that map to top-level of page

### ISSUE THREAD

**Issue by j-low** [algolia/docsearch-configs#570]
# Do you want to request a **feature** or report a **bug**?
Undesired behavior, not really a bug

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`= cockroachlabs

## What is the **current** behaviour?
`#main-content` ID gets appended to hit URLs that map to top-level page results.  When the link is opened, the browser jumps down to beginning of content.

![main-content](https://user-images.githubusercontent.com/6320333/45841195-0c063200-bce7-11e8-8522-4d6f49f0f3f1.png)

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

## What is the **expected** behaviour?
Ideally, we'd like top-level results to exclude `#main-content` ID from the URL.

#### What have you tried to solve it?
* removed `#main-content` from selectors
* looked through config docs for likely options to leverage

#### Any quick clues?
* `global` selector on `lvl0` might be what I'm looking for but I'm not totally sure about it

**Comment by s-pace** [comment]
Hi @j-low,

Thank you for the full description.

We do extract the `id` or `name` attribute from your HTML in order to do the best redirection. This is done by recursively looking into the parent of the current extracted element.

Since you are using a custom UI, could you add a `id` or `name` attribute to every elements matching the lvlX selectors? 

Note: if you are using the provided UI, you can have use the [`transformdata` method](https://community.algolia.com/docsearch/behavior.html#transformdata) method

**Comment by s-pace** [comment]
Hi @j-low 

It is not exactly what I meant. You do not need to change anything from your DocSearch configuration. The changes should be done within your HTML. It will define [the right anchor](https://www.w3.org/MarkUp/1995-archive/Elements/A.html) to pick up. Every elements, within your pages, matching a `lvlX` selectors should have a unique `id` or `name` parameter.

Example with this [`SQL Layer` page](https://www.cockroachlabs.com/docs/v2.0/architecture/sql-layer.html#main-content):

The element matching the `lvl0` does not have an `id` or `name` attribute set:
```html
<h1 class="post-title-main">SQL Layer</h1>
```
We would need something like:
```html
<h1 class="post-title-main" id="SQL-layer" >SQL Layer</h1>
```
The value of the attribute itself should only match the standard. 

In this precise page, you can note that if you are looking for `Once CockroachDB has been deployed, developers need nothing more than a connection string to the cluster and SQL statements to start working `, The anchor will not be `main-content` because the record is a `lvl1` one.

![image](https://user-images.githubusercontent.com/32097720/46336215-780f6100-c62a-11e8-88c5-80c8e0240696.png)

The matching element of the selectors `lvl1` (`.post-content h2`) do have a `id` attribute set. This is why we redirect to the correct anchor:

```html
<h2 id="overview" class="...">Overview...</h2>
```

We do not use `main-content` which is the fallback because it is the first anchor available in a ancestor element.

**Comment by s-pace** [comment]
Did it help @j-low ? Feel free to share your feedback and/or close it

**Comment by j-low** [comment]
@s-pace sorry for the delay.  We've got a release coming soon and I've been swamped with that.  I'll be working on this once that is wrapped.  Feel free to close it if you need to and I can reopen/create a new issue if this approach gives me issues.

Thanks again for help.
