### ISSUE TITLE
Issues with solace.json

### ISSUE THREAD

**Issue by ArshRai17** [algolia/docsearch-configs#736]
# Do you want to request a **feature** or report a **bug**?

### If it is a DocSearch index issue, what is the related `index_name` ?

`index_name`=solace

## What is the **current** behaviour?

*If the current behaviour is a bug, please provide all the steps to reproduce and screenshots with context.*

@s-pace , received some feedback from our users. I am not sure if this is the right place to post these; if not, please let me know what would be the best way highlight these issues.

- Crawler does not index all the pages. If you search for Cut-through Messaging, Transactions, or PCF Tile, the search does not show the page/title in the result. I have come across three pages, but there could be more. Here are those pages:
-- https://docs.solace.com/Messaging-Basics/Cut-Through-Msging.htm
-- https://docs.solace.com/Messaging-Basics/Transactions.htm
-- https://docs.solace.com/Solace-SW-Broker-Set-Up/Starting-SW-Brokers-for-the-First-Time/Set-Up-PCF.htm

- In the drop-down search results display, the text on the left hand column (`class="algolia-docsearch-suggestion--subcategory-column-text"`), in many instances, are the same as the content/title (see screenshot below). For example, when I search for “CLI command Scopes” the Docsearch suggestions on the left hand column (grayed out) and the right column (content/title) are the same, which does not provide any context to the user. I am not sure if this is due to the way our docs are structured or if updating the config file can resolve this. Though, I see this happening only with h2 headings.

Note the first two results below:

**Actual**
![image](https://user-images.githubusercontent.com/29955404/52655868-3093be00-2ec3-11e9-9449-4c2d23aa88a0.png)

**Expected**
![image](https://user-images.githubusercontent.com/29955404/52657822-7f435700-2ec7-11e9-856f-356fb5c995cb.png)

- Lastly, The `cli_command` selector in the JSON config only indexed the VMR CLI and not the Appliance CLI. For example, the `show hardware` command, which is an appliance specific command, does not give any result. Would it help if we define selectors for `vmr` and `appl` separately?

Thank you!

**Comment by s-pace** [comment]
Hi @ArshRai17 

I can confirm that these pages are not crawled. The reason is that these pages are not referenced from another crawled page without client side rendering. You can reproduce this issue by browsing the outcome of your pages fetched from a `curl` command.

- Please *[provide us a sitemap](https://community.algolia.com/docsearch/tips.html#use-a-sitemap.xml)* for your pages. Using client side rendering will be overkill to fix such issue.

As for the second point, the first hit is a record which has only a lvl0 and lvl1 defined while the lvl2 is not set. Our default UI is built this way:
![Reference](https://cl.ly/6fcd90fd889e/download/Image%202019-02-13%20at%209.58.19%20AM.png)

 Your custom Search-UI does not display the lvl0. The lvl2 reproduced the lvl1 since there is none (default behaviour of our UI). I can quickly fix it by shifting every selectors level to its lower one. You will not loose the valuable lvl0 information and it will avoid having this duplicate. The expected behaviour will be close to the one you have described on your screenshot. It will still happen for records that only have a lvl0 defined though.

If you do not want this default behaviour, you will need to edit this behaviour from your custom implementation. We recommend the use of our [dedicated UI library InstantSearch](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/).

Lastly https://docs.solace.com/Solace-CLI/CLI-Reference/APPL_CLI_Commands.html was not crawled at all. The reason are the same than the first point. [This change in your configuration](https://github.com/algolia/docsearch-configs/commit/db512ed69f515331b16898828e8684071d819481) solved it. The `show hardware` command is not retrievable from your search.

**Comment by ArshRai17** [comment]
Thanks for the updates. 

I don't understand this part: 

> "The reason is that these pages are not referenced from another crawled page without client side rendering."

Those pages are part of the docs.solace.com and are listed in our sitemap https://docs.solace.com/Sitemap.xml. I can add the sitemap to the config file, if that will help. However, since the sitemap is generated automatically, it does not add URL of the external pages such as the API ref, event ref, etc. If we do add the sitemap in the config file, I guess it won't impact the search configuration for the external pages?

It would be great if we can try shifting the selectors and see if that improves the hierarchy of the drop-down display. 

And, the appl ref index is working now, thanks!

**Comment by s-pace** [comment]
> I don't understand this part:

Our tool crawls a page (without sitemap) if the page is referenced from another already crawled page. It follows link, e.g. <a/> tag. The missing page is not referenced from another one because these <a/> tags are only created thanks to client side rendering. If you could avoid to render your navigation bar in this way, it will be correctly crawled. You can also create a dedicated sitemap gathering all these external pages.

You can check the changes introduce by this quick fix on your website, it is live.

**Comment by ArshRai17** [comment]
Thanks for the prompt response!

> Your custom Search-UI does not display the lvl0. The lvl2 reproduced the lvl1 since there is none (default behaviour of our UI). I can quickly fix it by shifting every selectors level to its lower one. You will not loose the valuable lvl0 information and it will avoid having this duplicate. The expected behaviour will be close to the one you have described on your screenshot. It will still happen for records that only have a lvl0 defined though.

The behavior is still the same. If you search for "CLI Command Scopes" the search results are the same as before; Lvl 2 title is duplicated in both the columns. I think, the ideal solution will be to have the items on the table of contents as level 0, followed by h1, then h2...in that manner. This obviously requires us to do further configuration.

> You can check the changes introduce by this quick fix on your website, it is live.

Even with the sitemap, it is still not possible to find the following pages using search:

- https://docs.solace.com/Messaging-Basics/Cut-Through-Msging.htm
- https://docs.solace.com/Messaging-Basics/Transactions.htm
- https://docs.solace.com/Solace-SW-Broker-Set-Up/Starting-SW-Brokers-for-the-First-Time/Set-Up-PCF.htm

Its' strange that these pages are not crawled as they are part of our documentation, unlike the Event or CLI references. Maybe we should give it day for the crawler to work?

**Comment by s-pace** [comment]
You are welcome.

The search results looks better and are more close to what you have expected. You can have a look on this screenshot from your website:
![image](https://user-images.githubusercontent.com/32097720/52770533-a9b22300-3033-11e9-81b0-42675aa7240c.png)

Lvl2 will always be duplicated since it is empty. Using the table of content is not possible since it is only rendered via javascript. The easiest solution would be to edit your custom search UI to prevent such behaviour. You can also add a DOM element within your page that give this lvl1 information. You will need to add it from your configuration then.

The pages you have mentioned can be retrieved:

![image](https://user-images.githubusercontent.com/32097720/52770618-e120cf80-3033-11e9-8872-48e3d9557bb3.png)

![image](https://user-images.githubusercontent.com/32097720/52770669-ff86cb00-3033-11e9-9045-199affd09511.png)

![image](https://user-images.githubusercontent.com/32097720/52770695-10cfd780-3034-11e9-8535-eec68ee10758.png)

**Comment by ArshRai17** [comment]
> The search results looks better and are more close to what you have expected.

Thanks, @s-pace. I will close this issued. Cheers!
