### ISSUE TITLE
[question]: adding packages/ from monorepo to index (gatsby)

### ISSUE THREAD

**Issue by DSchau** [algolia/docsearch-configs#783]
# Do you want to request a **feature** or report a **bug**?

Bug, but it's really more of a question!

### If it is a DocSearch index issue, what is the related `index_name` ?

n/a

## What is the **current** behaviour?

Package content, e.g. README.md, seem to not be searchable via our Algolia index/search.

For instance, we have [`gatsby-source-filesystem`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-filesystem) which contains `createFilePath` in its README.md. Searching for `createFilePath` from [gatsbyjs.org](https://gatsbyjs.org) does not find the correct content--or any, for that matter!

## What is the **expected** behaviour?

Packages are indexable and can be searched (or some workaround for getting this working!).

#### What have you tried to solve it?

Sorry - don't have a ton of insight into this. We've opened up gatsbyjs/gatsby#12503, which surfaced [01178d485d238968151d4dddd95d85621737afad](https://github.com/algolia/docsearch-configs/commit/01178d485d238968151d4dddd95d85621737afad) which appears to have proactively removed `packages/*` from the index, but not sure how else to debug!

#### Any quick clues?

n/a

### Any other feedback / questions ?

We're happy to help solve this ourselves--just not sure how to best start doing that.

Thank you--we love using Algolia 💜

**Comment by s-pace** [comment]
👋 @DSchau,

Thank you for your feedback.

Pages available from URL /packages/* are not searchable. We have removed them since you are already using an Algolia index [for searching these packages](https://www.gatsbyjs.org/plugins/).

We can make these packages available from the search but it will require some updates from your side to make the layout of the page consistent. It will also double the number of records, which can introduce noise regarding the documentation search. I can list you the changes required if you want to give it a try.

In the meantime, you can [try out the current state of this search with this temporal index here](https://community.algolia.com/docsearch-preview/index.html?apiKey=36aa11773393a7650ec4f09cd4a3bc7c&indexName=dev_gatsbyjs&appId=Y7BGGRAPHC). Do not use this in production as it is not updated.

**Comment by s-pace** [comment]
Closing this issues at it was inactive for more than 30 days, @DSchau feel free to reopen it if needed.
